title: "Kronos Zone"
description: "Servidor Minecraft | Servidor competitivo"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"  # tema robusto con navbar, hero, etc.
minimal_mistakes_skin: "dark"  # prueba: default, dark, neon, air, etc.

# URL de tu sitio (ajústala cuando tengas el dominio o la URL de GitHub Pages)
url: "http://www.kronoszone.me"
baseurl: ""

logo: "/assets/img/logo2.png"  # opcional (para la cabecera compacta)
repository: "vicebarrientos/vicebarrientos.github.io"

# Navegación principal (desde _data/navigation.yml)
collections:
  changelogs:
    output: true
    permalink: /changelogs/:name/

# Plugins que usa el tema (GitHub Pages los soporta)
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO/Meta
author:
  name: "Kronos Zone"
  avatar: "/assets/img/logo2.png"
  bio: "Servidor Minecraft en español"
  links:
    - label: "Discord"
      url: "https://discord.gg/tu-invite"
    - label: "IP del servidor"
      url: "#"

sass:
  style: compressed

# Opciones de layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      toc: false
  - scope:
      path: ""
      type: "changelogs"
    values:
      layout: "single"
      toc: false
